1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code or functions that provide functionality to perform specific tasks. These libraries are designed to be reused by developers to simplify their programming tasks and avoid reinventing the wheel for common functionalities.

There are several reasons why we use Python libraries:
1) Code Reusability
2) Efficiency
3) Specialized Functionality
4) Community Support
5) Standardization


2. What is the difference between Numpy array and List?

NumPy arrays are more suitable for numerical computations and large datasets due to their efficiency, performance, and extensive functionality, while Python lists offer more flexibility and simplicity for general-purpose use cases.

NumPy arrays and Python lists are both used to store collections of elements, but they have some fundamental differences:

1) Data Type:

NumPy arrays are homogeneous, meaning all elements must have the same data type (e.g., integers, floats, etc.

Python lists are heterogeneous, meaning they can contain elements of different data types.

2) Memory Efficiency:
   
NumPy arrays are more memory efficient compared to Python lists, especially for large datasets. This is because NumPy arrays store data in contiguous blocks of memory, while Python lists store references to objects scattered throughout memory.

4) Peformance:
   
NumPy operations on arrays are typically faster than equivalent operations on Python lists. This is due to NumPy's ability to leverage vectorized operations and optimized C code implementations.

6) Functionality:
   
NumPy arrays offer a wide range of mathematical and array manipulation functions that are optimized for performance. These functions include element-wise operations, linear algebra operations, statistical functions, and more.

Python lists provide basic functionalities for storing and manipulating collections of elements. While lists offer some built-in methods (e.g., append, extend, insert), they do not provide as extensive functionality as NumPy arrays

5) Syntax and Usage:
   
NumPy arrays are created using the numpy.array() function and accessed using indexing, slicing, and broadcasting operations similar to standard arrays in other programming languages.

Python lists are created using square brackets ([]) and support a wide range of operations and manipulations through built-in methods and functions..).).

3. Find the shape, size and dimension of the following array?
   
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr.shape

(3, 4)

In [7]:
arr.size

12

In [8]:
arr.ndim

2

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [21]:
arr1 = np.random.randint(0,2,size = (3,3))

In [22]:
arr1

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 1]])

8. Describe the difference between np.random.rand and np.random.randn?

 the main difference between np.random.rand and np.random.randn lies in the distributions they generate random numbers from:

 np.random.rand generates random numbers from a uniform distribution between 0 and 1

In [23]:
np.random.rand(3,3)

array([[0.28292424, 0.39091731, 0.62041411],
       [0.16017505, 0.59409918, 0.92839482],
       [0.32713009, 0.29617115, 0.52081156]])

np.random.randn generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.

In [24]:
np.random.randn(3,3)

array([[ 7.43852573e-01,  2.09594712e+00, -2.64489181e-01],
       [ 5.75545799e-01, -1.66276134e-03,  7.51835415e-01],
       [ 1.15614261e+00, -1.17859009e+00,  1.47790730e+00]])

9. Write code to increase the dimension of the following array?
    
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [31]:
print(arr)
print("The dimension of the array is:",arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The dimension of the array is: 2


In [32]:
arr1 = np.expand_dims(arr, axis = 0)
print(arr1)
print("The dimension got expanded from 2 to 3",arr1.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
The dimension got expanded from 2 to 3 3


10. How to transpose the following array in NumPy?
    
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [33]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
    
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python

1) Index wise multiplication

In [40]:
a2 = np.matrix(arr)
b2 = np.matrix(arr)

In [41]:
a2

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [42]:
b2

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [57]:
# Index wise multiplication
# here we need to take the transpose of b2 because
#to perform index wise multiplication b/w mxn & pxq
# n == p
# we can do index wise multiplication of arrays of any sizes
a2 * b2.T

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

2) Matix multiplication

In [49]:
# here we need to take the transpose of b2 because
#to perform index wise multiplication b/w mxn & pxq
a2 @ b2.T

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

3) Add both the maticx

In [50]:
a2 + b2

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

4) Subtact matix B from A

In [51]:
b2 - a2

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

5) Divide matrix B by A

In [53]:
b2 / a2

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?

In [54]:
# np.byteswap is used to swap the byte order of an array
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr.byteswap()

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in its utility for solving systems of linear equations, performing matrix division, and in various mathematical and scientific computations. Here's why it's significant:

1) Solving Systems of Linear Equations
2) Matrix Division
3) Eigenvalue and Eigenvector Calculations
4) Numerical Stability
5) Inverse Matrices in Linear Algebra


In [59]:
ar = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.inv(ar)

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

14. What does the np.reshape function do, and how is it used?

In [60]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
arr.ndim

2

In [62]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [63]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

15. What is broadcasting in Numpy?

In [64]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10, 20, 30])

In [65]:
a + b

array([[11, 22, 33],
       [14, 25, 36]])